# Can use the -auto-approve flag after the apply and destroy commands

run:
	terraform init
	terraform apply

fmt:
	terraform fmt
	terraform validate

destroy:
	terraform destroy

clean:
	terraform destroy 
	rm -rf terraform.*
	rm -rf .terraform*

